// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package maas

import (
	"context"
	"reflect"

	"errors"
	"github.com/juhnny5/pulumi-maas/sdk/go/maas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DnsRecord struct {
	pulumi.CustomResourceState

	// The data set for the new DNS record.
	Data pulumi.StringOutput `pulumi:"data"`
	// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
	Domain pulumi.StringPtrOutput `pulumi:"domain"`
	// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
	// conflicts with `name` and `domain` arguments.
	Fqdn pulumi.StringPtrOutput `pulumi:"fqdn"`
	// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
	Name pulumi.StringOutput `pulumi:"name"`
	// The TTL of the new DNS record.
	Ttl pulumi.IntPtrOutput `pulumi:"ttl"`
	// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewDnsRecord registers a new resource with the given unique name, arguments, and options.
func NewDnsRecord(ctx *pulumi.Context,
	name string, args *DnsRecordArgs, opts ...pulumi.ResourceOption) (*DnsRecord, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Data == nil {
		return nil, errors.New("invalid value for required argument 'Data'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DnsRecord
	err := ctx.RegisterResource("maas:index/dnsRecord:DnsRecord", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDnsRecord gets an existing DnsRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDnsRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsRecordState, opts ...pulumi.ResourceOption) (*DnsRecord, error) {
	var resource DnsRecord
	err := ctx.ReadResource("maas:index/dnsRecord:DnsRecord", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DnsRecord resources.
type dnsRecordState struct {
	// The data set for the new DNS record.
	Data *string `pulumi:"data"`
	// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
	Domain *string `pulumi:"domain"`
	// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
	// conflicts with `name` and `domain` arguments.
	Fqdn *string `pulumi:"fqdn"`
	// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
	Name *string `pulumi:"name"`
	// The TTL of the new DNS record.
	Ttl *int `pulumi:"ttl"`
	// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
	Type *string `pulumi:"type"`
}

type DnsRecordState struct {
	// The data set for the new DNS record.
	Data pulumi.StringPtrInput
	// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
	Domain pulumi.StringPtrInput
	// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
	// conflicts with `name` and `domain` arguments.
	Fqdn pulumi.StringPtrInput
	// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
	Name pulumi.StringPtrInput
	// The TTL of the new DNS record.
	Ttl pulumi.IntPtrInput
	// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
	Type pulumi.StringPtrInput
}

func (DnsRecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsRecordState)(nil)).Elem()
}

type dnsRecordArgs struct {
	// The data set for the new DNS record.
	Data string `pulumi:"data"`
	// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
	Domain *string `pulumi:"domain"`
	// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
	// conflicts with `name` and `domain` arguments.
	Fqdn *string `pulumi:"fqdn"`
	// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
	Name *string `pulumi:"name"`
	// The TTL of the new DNS record.
	Ttl *int `pulumi:"ttl"`
	// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a DnsRecord resource.
type DnsRecordArgs struct {
	// The data set for the new DNS record.
	Data pulumi.StringInput
	// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
	Domain pulumi.StringPtrInput
	// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
	// conflicts with `name` and `domain` arguments.
	Fqdn pulumi.StringPtrInput
	// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
	Name pulumi.StringPtrInput
	// The TTL of the new DNS record.
	Ttl pulumi.IntPtrInput
	// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
	Type pulumi.StringInput
}

func (DnsRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsRecordArgs)(nil)).Elem()
}

type DnsRecordInput interface {
	pulumi.Input

	ToDnsRecordOutput() DnsRecordOutput
	ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput
}

func (*DnsRecord) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsRecord)(nil)).Elem()
}

func (i *DnsRecord) ToDnsRecordOutput() DnsRecordOutput {
	return i.ToDnsRecordOutputWithContext(context.Background())
}

func (i *DnsRecord) ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsRecordOutput)
}

// DnsRecordArrayInput is an input type that accepts DnsRecordArray and DnsRecordArrayOutput values.
// You can construct a concrete instance of `DnsRecordArrayInput` via:
//
//	DnsRecordArray{ DnsRecordArgs{...} }
type DnsRecordArrayInput interface {
	pulumi.Input

	ToDnsRecordArrayOutput() DnsRecordArrayOutput
	ToDnsRecordArrayOutputWithContext(context.Context) DnsRecordArrayOutput
}

type DnsRecordArray []DnsRecordInput

func (DnsRecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DnsRecord)(nil)).Elem()
}

func (i DnsRecordArray) ToDnsRecordArrayOutput() DnsRecordArrayOutput {
	return i.ToDnsRecordArrayOutputWithContext(context.Background())
}

func (i DnsRecordArray) ToDnsRecordArrayOutputWithContext(ctx context.Context) DnsRecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsRecordArrayOutput)
}

// DnsRecordMapInput is an input type that accepts DnsRecordMap and DnsRecordMapOutput values.
// You can construct a concrete instance of `DnsRecordMapInput` via:
//
//	DnsRecordMap{ "key": DnsRecordArgs{...} }
type DnsRecordMapInput interface {
	pulumi.Input

	ToDnsRecordMapOutput() DnsRecordMapOutput
	ToDnsRecordMapOutputWithContext(context.Context) DnsRecordMapOutput
}

type DnsRecordMap map[string]DnsRecordInput

func (DnsRecordMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DnsRecord)(nil)).Elem()
}

func (i DnsRecordMap) ToDnsRecordMapOutput() DnsRecordMapOutput {
	return i.ToDnsRecordMapOutputWithContext(context.Background())
}

func (i DnsRecordMap) ToDnsRecordMapOutputWithContext(ctx context.Context) DnsRecordMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsRecordMapOutput)
}

type DnsRecordOutput struct{ *pulumi.OutputState }

func (DnsRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsRecord)(nil)).Elem()
}

func (o DnsRecordOutput) ToDnsRecordOutput() DnsRecordOutput {
	return o
}

func (o DnsRecordOutput) ToDnsRecordOutputWithContext(ctx context.Context) DnsRecordOutput {
	return o
}

// The data set for the new DNS record.
func (o DnsRecordOutput) Data() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Data }).(pulumi.StringOutput)
}

// The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
func (o DnsRecordOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringPtrOutput { return v.Domain }).(pulumi.StringPtrOutput)
}

// The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
// conflicts with `name` and `domain` arguments.
func (o DnsRecordOutput) Fqdn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringPtrOutput { return v.Fqdn }).(pulumi.StringPtrOutput)
}

// The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
func (o DnsRecordOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The TTL of the new DNS record.
func (o DnsRecordOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.IntPtrOutput { return v.Ttl }).(pulumi.IntPtrOutput)
}

// The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
func (o DnsRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsRecord) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type DnsRecordArrayOutput struct{ *pulumi.OutputState }

func (DnsRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DnsRecord)(nil)).Elem()
}

func (o DnsRecordArrayOutput) ToDnsRecordArrayOutput() DnsRecordArrayOutput {
	return o
}

func (o DnsRecordArrayOutput) ToDnsRecordArrayOutputWithContext(ctx context.Context) DnsRecordArrayOutput {
	return o
}

func (o DnsRecordArrayOutput) Index(i pulumi.IntInput) DnsRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DnsRecord {
		return vs[0].([]*DnsRecord)[vs[1].(int)]
	}).(DnsRecordOutput)
}

type DnsRecordMapOutput struct{ *pulumi.OutputState }

func (DnsRecordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DnsRecord)(nil)).Elem()
}

func (o DnsRecordMapOutput) ToDnsRecordMapOutput() DnsRecordMapOutput {
	return o
}

func (o DnsRecordMapOutput) ToDnsRecordMapOutputWithContext(ctx context.Context) DnsRecordMapOutput {
	return o
}

func (o DnsRecordMapOutput) MapIndex(k pulumi.StringInput) DnsRecordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DnsRecord {
		return vs[0].(map[string]*DnsRecord)[vs[1].(string)]
	}).(DnsRecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsRecordInput)(nil)).Elem(), &DnsRecord{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnsRecordArrayInput)(nil)).Elem(), DnsRecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnsRecordMapInput)(nil)).Elem(), DnsRecordMap{})
	pulumi.RegisterOutputType(DnsRecordOutput{})
	pulumi.RegisterOutputType(DnsRecordArrayOutput{})
	pulumi.RegisterOutputType(DnsRecordMapOutput{})
}
