// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package maas

import (
	"context"
	"reflect"

	"github.com/juhnny5/pulumi-maas/sdk/go/maas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupFabric(ctx *pulumi.Context, args *LookupFabricArgs, opts ...pulumi.InvokeOption) (*LookupFabricResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFabricResult
	err := ctx.Invoke("maas:index/getFabric:getFabric", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFabric.
type LookupFabricArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getFabric.
type LookupFabricResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}

func LookupFabricOutput(ctx *pulumi.Context, args LookupFabricOutputArgs, opts ...pulumi.InvokeOption) LookupFabricResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFabricResult, error) {
			args := v.(LookupFabricArgs)
			r, err := LookupFabric(ctx, &args, opts...)
			var s LookupFabricResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFabricResultOutput)
}

// A collection of arguments for invoking getFabric.
type LookupFabricOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupFabricOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFabricArgs)(nil)).Elem()
}

// A collection of values returned by getFabric.
type LookupFabricResultOutput struct{ *pulumi.OutputState }

func (LookupFabricResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFabricResult)(nil)).Elem()
}

func (o LookupFabricResultOutput) ToLookupFabricResultOutput() LookupFabricResultOutput {
	return o
}

func (o LookupFabricResultOutput) ToLookupFabricResultOutputWithContext(ctx context.Context) LookupFabricResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupFabricResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFabricResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFabricResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFabricResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFabricResultOutput{})
}
