// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package maas

import (
	"context"
	"reflect"

	"github.com/juhnny5/pulumi-maas/sdk/go/maas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupVlan(ctx *pulumi.Context, args *LookupVlanArgs, opts ...pulumi.InvokeOption) (*LookupVlanResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVlanResult
	err := ctx.Invoke("maas:index/getVlan:getVlan", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVlan.
type LookupVlanArgs struct {
	Fabric string `pulumi:"fabric"`
	Vlan   string `pulumi:"vlan"`
}

// A collection of values returned by getVlan.
type LookupVlanResult struct {
	DhcpOn bool   `pulumi:"dhcpOn"`
	Fabric string `pulumi:"fabric"`
	// The provider-assigned unique ID for this managed resource.
	Id    string `pulumi:"id"`
	Mtu   int    `pulumi:"mtu"`
	Name  string `pulumi:"name"`
	Space string `pulumi:"space"`
	Vlan  string `pulumi:"vlan"`
}

func LookupVlanOutput(ctx *pulumi.Context, args LookupVlanOutputArgs, opts ...pulumi.InvokeOption) LookupVlanResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupVlanResult, error) {
			args := v.(LookupVlanArgs)
			r, err := LookupVlan(ctx, &args, opts...)
			var s LookupVlanResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupVlanResultOutput)
}

// A collection of arguments for invoking getVlan.
type LookupVlanOutputArgs struct {
	Fabric pulumi.StringInput `pulumi:"fabric"`
	Vlan   pulumi.StringInput `pulumi:"vlan"`
}

func (LookupVlanOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanArgs)(nil)).Elem()
}

// A collection of values returned by getVlan.
type LookupVlanResultOutput struct{ *pulumi.OutputState }

func (LookupVlanResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanResult)(nil)).Elem()
}

func (o LookupVlanResultOutput) ToLookupVlanResultOutput() LookupVlanResultOutput {
	return o
}

func (o LookupVlanResultOutput) ToLookupVlanResultOutputWithContext(ctx context.Context) LookupVlanResultOutput {
	return o
}

func (o LookupVlanResultOutput) DhcpOn() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVlanResult) bool { return v.DhcpOn }).(pulumi.BoolOutput)
}

func (o LookupVlanResultOutput) Fabric() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Fabric }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVlanResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupVlanResultOutput) Mtu() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVlanResult) int { return v.Mtu }).(pulumi.IntOutput)
}

func (o LookupVlanResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupVlanResultOutput) Space() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Space }).(pulumi.StringOutput)
}

func (o LookupVlanResultOutput) Vlan() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Vlan }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVlanResultOutput{})
}
