// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package maas

import (
	"context"
	"reflect"

	"errors"
	"github.com/juhnny5/pulumi-maas/sdk/go/maas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VmHostMachine struct {
	pulumi.CustomResourceState

	// The number of CPU cores (defaults to 1).
	Cores pulumi.IntPtrOutput `pulumi:"cores"`
	// The VM host machine domain. This is computed if it's not set.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// The VM host machine hostname. This is computed if it's not set.
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory pulumi.IntPtrOutput `pulumi:"memory"`
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
	// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
	// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces VmHostMachineNetworkInterfaceArrayOutput `pulumi:"networkInterfaces"`
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores pulumi.IntPtrOutput `pulumi:"pinnedCores"`
	// The VM host machine pool. This is computed if it's not set.
	Pool pulumi.StringOutput `pulumi:"pool"`
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
	// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	StorageDisks VmHostMachineStorageDiskArrayOutput `pulumi:"storageDisks"`
	// ID or name of the VM host used to compose the new machine.
	VmHost pulumi.StringOutput `pulumi:"vmHost"`
	// The VM host machine zone. This is computed if it's not set.
	Zone pulumi.StringOutput `pulumi:"zone"`
}

// NewVmHostMachine registers a new resource with the given unique name, arguments, and options.
func NewVmHostMachine(ctx *pulumi.Context,
	name string, args *VmHostMachineArgs, opts ...pulumi.ResourceOption) (*VmHostMachine, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.VmHost == nil {
		return nil, errors.New("invalid value for required argument 'VmHost'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VmHostMachine
	err := ctx.RegisterResource("maas:index/vmHostMachine:VmHostMachine", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVmHostMachine gets an existing VmHostMachine resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVmHostMachine(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VmHostMachineState, opts ...pulumi.ResourceOption) (*VmHostMachine, error) {
	var resource VmHostMachine
	err := ctx.ReadResource("maas:index/vmHostMachine:VmHostMachine", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VmHostMachine resources.
type vmHostMachineState struct {
	// The number of CPU cores (defaults to 1).
	Cores *int `pulumi:"cores"`
	// The VM host machine domain. This is computed if it's not set.
	Domain *string `pulumi:"domain"`
	// The VM host machine hostname. This is computed if it's not set.
	Hostname *string `pulumi:"hostname"`
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory *int `pulumi:"memory"`
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
	// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
	// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces []VmHostMachineNetworkInterface `pulumi:"networkInterfaces"`
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores *int `pulumi:"pinnedCores"`
	// The VM host machine pool. This is computed if it's not set.
	Pool *string `pulumi:"pool"`
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
	// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	StorageDisks []VmHostMachineStorageDisk `pulumi:"storageDisks"`
	// ID or name of the VM host used to compose the new machine.
	VmHost *string `pulumi:"vmHost"`
	// The VM host machine zone. This is computed if it's not set.
	Zone *string `pulumi:"zone"`
}

type VmHostMachineState struct {
	// The number of CPU cores (defaults to 1).
	Cores pulumi.IntPtrInput
	// The VM host machine domain. This is computed if it's not set.
	Domain pulumi.StringPtrInput
	// The VM host machine hostname. This is computed if it's not set.
	Hostname pulumi.StringPtrInput
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory pulumi.IntPtrInput
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
	// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
	// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces VmHostMachineNetworkInterfaceArrayInput
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores pulumi.IntPtrInput
	// The VM host machine pool. This is computed if it's not set.
	Pool pulumi.StringPtrInput
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
	// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	StorageDisks VmHostMachineStorageDiskArrayInput
	// ID or name of the VM host used to compose the new machine.
	VmHost pulumi.StringPtrInput
	// The VM host machine zone. This is computed if it's not set.
	Zone pulumi.StringPtrInput
}

func (VmHostMachineState) ElementType() reflect.Type {
	return reflect.TypeOf((*vmHostMachineState)(nil)).Elem()
}

type vmHostMachineArgs struct {
	// The number of CPU cores (defaults to 1).
	Cores *int `pulumi:"cores"`
	// The VM host machine domain. This is computed if it's not set.
	Domain *string `pulumi:"domain"`
	// The VM host machine hostname. This is computed if it's not set.
	Hostname *string `pulumi:"hostname"`
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory *int `pulumi:"memory"`
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
	// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
	// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces []VmHostMachineNetworkInterface `pulumi:"networkInterfaces"`
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores *int `pulumi:"pinnedCores"`
	// The VM host machine pool. This is computed if it's not set.
	Pool *string `pulumi:"pool"`
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
	// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	StorageDisks []VmHostMachineStorageDisk `pulumi:"storageDisks"`
	// ID or name of the VM host used to compose the new machine.
	VmHost string `pulumi:"vmHost"`
	// The VM host machine zone. This is computed if it's not set.
	Zone *string `pulumi:"zone"`
}

// The set of arguments for constructing a VmHostMachine resource.
type VmHostMachineArgs struct {
	// The number of CPU cores (defaults to 1).
	Cores pulumi.IntPtrInput
	// The VM host machine domain. This is computed if it's not set.
	Domain pulumi.StringPtrInput
	// The VM host machine hostname. This is computed if it's not set.
	Hostname pulumi.StringPtrInput
	// The VM host machine RAM memory, specified in MB (defaults to 2048).
	Memory pulumi.IntPtrInput
	// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
	// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
	// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	NetworkInterfaces VmHostMachineNetworkInterfaceArrayInput
	// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
	PinnedCores pulumi.IntPtrInput
	// The VM host machine pool. This is computed if it's not set.
	Pool pulumi.StringPtrInput
	// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
	// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
	StorageDisks VmHostMachineStorageDiskArrayInput
	// ID or name of the VM host used to compose the new machine.
	VmHost pulumi.StringInput
	// The VM host machine zone. This is computed if it's not set.
	Zone pulumi.StringPtrInput
}

func (VmHostMachineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vmHostMachineArgs)(nil)).Elem()
}

type VmHostMachineInput interface {
	pulumi.Input

	ToVmHostMachineOutput() VmHostMachineOutput
	ToVmHostMachineOutputWithContext(ctx context.Context) VmHostMachineOutput
}

func (*VmHostMachine) ElementType() reflect.Type {
	return reflect.TypeOf((**VmHostMachine)(nil)).Elem()
}

func (i *VmHostMachine) ToVmHostMachineOutput() VmHostMachineOutput {
	return i.ToVmHostMachineOutputWithContext(context.Background())
}

func (i *VmHostMachine) ToVmHostMachineOutputWithContext(ctx context.Context) VmHostMachineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmHostMachineOutput)
}

// VmHostMachineArrayInput is an input type that accepts VmHostMachineArray and VmHostMachineArrayOutput values.
// You can construct a concrete instance of `VmHostMachineArrayInput` via:
//
//	VmHostMachineArray{ VmHostMachineArgs{...} }
type VmHostMachineArrayInput interface {
	pulumi.Input

	ToVmHostMachineArrayOutput() VmHostMachineArrayOutput
	ToVmHostMachineArrayOutputWithContext(context.Context) VmHostMachineArrayOutput
}

type VmHostMachineArray []VmHostMachineInput

func (VmHostMachineArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VmHostMachine)(nil)).Elem()
}

func (i VmHostMachineArray) ToVmHostMachineArrayOutput() VmHostMachineArrayOutput {
	return i.ToVmHostMachineArrayOutputWithContext(context.Background())
}

func (i VmHostMachineArray) ToVmHostMachineArrayOutputWithContext(ctx context.Context) VmHostMachineArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmHostMachineArrayOutput)
}

// VmHostMachineMapInput is an input type that accepts VmHostMachineMap and VmHostMachineMapOutput values.
// You can construct a concrete instance of `VmHostMachineMapInput` via:
//
//	VmHostMachineMap{ "key": VmHostMachineArgs{...} }
type VmHostMachineMapInput interface {
	pulumi.Input

	ToVmHostMachineMapOutput() VmHostMachineMapOutput
	ToVmHostMachineMapOutputWithContext(context.Context) VmHostMachineMapOutput
}

type VmHostMachineMap map[string]VmHostMachineInput

func (VmHostMachineMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VmHostMachine)(nil)).Elem()
}

func (i VmHostMachineMap) ToVmHostMachineMapOutput() VmHostMachineMapOutput {
	return i.ToVmHostMachineMapOutputWithContext(context.Background())
}

func (i VmHostMachineMap) ToVmHostMachineMapOutputWithContext(ctx context.Context) VmHostMachineMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmHostMachineMapOutput)
}

type VmHostMachineOutput struct{ *pulumi.OutputState }

func (VmHostMachineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VmHostMachine)(nil)).Elem()
}

func (o VmHostMachineOutput) ToVmHostMachineOutput() VmHostMachineOutput {
	return o
}

func (o VmHostMachineOutput) ToVmHostMachineOutputWithContext(ctx context.Context) VmHostMachineOutput {
	return o
}

// The number of CPU cores (defaults to 1).
func (o VmHostMachineOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.IntPtrOutput { return v.Cores }).(pulumi.IntPtrOutput)
}

// The VM host machine domain. This is computed if it's not set.
func (o VmHostMachineOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// The VM host machine hostname. This is computed if it's not set.
func (o VmHostMachineOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// The VM host machine RAM memory, specified in MB (defaults to 2048).
func (o VmHostMachineOutput) Memory() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.IntPtrOutput { return v.Memory }).(pulumi.IntPtrOutput)
}

// A list of network interfaces for new the VM host. This argument only works when the VM host is deployed from a
// registered MAAS machine. Parameters defined below. This argument is processed in [attribute-as-blocks
// mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
func (o VmHostMachineOutput) NetworkInterfaces() VmHostMachineNetworkInterfaceArrayOutput {
	return o.ApplyT(func(v *VmHostMachine) VmHostMachineNetworkInterfaceArrayOutput { return v.NetworkInterfaces }).(VmHostMachineNetworkInterfaceArrayOutput)
}

// List of host CPU cores to pin the VM host machine to. If this is passed, the `cores` parameter is ignored.
func (o VmHostMachineOutput) PinnedCores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.IntPtrOutput { return v.PinnedCores }).(pulumi.IntPtrOutput)
}

// The VM host machine pool. This is computed if it's not set.
func (o VmHostMachineOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

// A list of storage disks for the new VM host. Parameters defined below. This argument is processed in
// [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html).
func (o VmHostMachineOutput) StorageDisks() VmHostMachineStorageDiskArrayOutput {
	return o.ApplyT(func(v *VmHostMachine) VmHostMachineStorageDiskArrayOutput { return v.StorageDisks }).(VmHostMachineStorageDiskArrayOutput)
}

// ID or name of the VM host used to compose the new machine.
func (o VmHostMachineOutput) VmHost() pulumi.StringOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.StringOutput { return v.VmHost }).(pulumi.StringOutput)
}

// The VM host machine zone. This is computed if it's not set.
func (o VmHostMachineOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v *VmHostMachine) pulumi.StringOutput { return v.Zone }).(pulumi.StringOutput)
}

type VmHostMachineArrayOutput struct{ *pulumi.OutputState }

func (VmHostMachineArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VmHostMachine)(nil)).Elem()
}

func (o VmHostMachineArrayOutput) ToVmHostMachineArrayOutput() VmHostMachineArrayOutput {
	return o
}

func (o VmHostMachineArrayOutput) ToVmHostMachineArrayOutputWithContext(ctx context.Context) VmHostMachineArrayOutput {
	return o
}

func (o VmHostMachineArrayOutput) Index(i pulumi.IntInput) VmHostMachineOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VmHostMachine {
		return vs[0].([]*VmHostMachine)[vs[1].(int)]
	}).(VmHostMachineOutput)
}

type VmHostMachineMapOutput struct{ *pulumi.OutputState }

func (VmHostMachineMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VmHostMachine)(nil)).Elem()
}

func (o VmHostMachineMapOutput) ToVmHostMachineMapOutput() VmHostMachineMapOutput {
	return o
}

func (o VmHostMachineMapOutput) ToVmHostMachineMapOutputWithContext(ctx context.Context) VmHostMachineMapOutput {
	return o
}

func (o VmHostMachineMapOutput) MapIndex(k pulumi.StringInput) VmHostMachineOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VmHostMachine {
		return vs[0].(map[string]*VmHostMachine)[vs[1].(string)]
	}).(VmHostMachineOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VmHostMachineInput)(nil)).Elem(), &VmHostMachine{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmHostMachineArrayInput)(nil)).Elem(), VmHostMachineArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmHostMachineMapInput)(nil)).Elem(), VmHostMachineMap{})
	pulumi.RegisterOutputType(VmHostMachineOutput{})
	pulumi.RegisterOutputType(VmHostMachineArrayOutput{})
	pulumi.RegisterOutputType(VmHostMachineMapOutput{})
}
