// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/juhnny5/pulumi-maas/sdk/go/maas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The MAAS API key
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "maas:apiKey")
}

// The MAAS API URL (eg: http://127.0.0.1:5240/MAAS)
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "maas:apiUrl")
}

// The MAAS API version (default 2.0)
func GetApiVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "maas:apiVersion")
}
