// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface BlockDevicePartition {
    bootable?: pulumi.Input<boolean>;
    fsType?: pulumi.Input<string>;
    label?: pulumi.Input<string>;
    mountOptions?: pulumi.Input<string>;
    mountPoint?: pulumi.Input<string>;
    path?: pulumi.Input<string>;
    sizeGigabytes: pulumi.Input<number>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface InstanceAllocateParams {
    hostname?: pulumi.Input<string>;
    minCpuCount?: pulumi.Input<number>;
    minMemory?: pulumi.Input<number>;
    pool?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    zone?: pulumi.Input<string>;
}

export interface InstanceDeployParams {
    distroSeries?: pulumi.Input<string>;
    enableHwSync?: pulumi.Input<boolean>;
    hweKernel?: pulumi.Input<string>;
    userData?: pulumi.Input<string>;
}

export interface InstanceNetworkInterface {
    ipAddress?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    subnetCidr?: pulumi.Input<string>;
}

export interface SubnetIpRange {
    comment?: pulumi.Input<string>;
    endIp: pulumi.Input<string>;
    startIp: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface VmHostMachineNetworkInterface {
    fabric?: pulumi.Input<string>;
    ipAddress?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    subnetCidr?: pulumi.Input<string>;
    vlan?: pulumi.Input<string>;
}

export interface VmHostMachineStorageDisk {
    pool?: pulumi.Input<string>;
    sizeGigabytes: pulumi.Input<number>;
}
