// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsDomain extends pulumi.CustomResource {
    /**
     * Get an existing DnsDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsDomainState, opts?: pulumi.CustomResourceOptions): DnsDomain {
        return new DnsDomain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'maas:index/dnsDomain:DnsDomain';

    /**
     * Returns true if the given object is an instance of DnsDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsDomain.__pulumiType;
    }

    /**
     * Boolean value indicating if the new DNS domain is authoritative. Defaults to `false`.
     */
    public readonly authoritative!: pulumi.Output<boolean | undefined>;
    /**
     * Boolean value indicating if the new DNS domain will be set as the default in the MAAS environment. Defaults to `false`.
     */
    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    /**
     * The name of the new DNS domain.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The default TTL for the new DNS domain.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;

    /**
     * Create a DnsDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DnsDomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsDomainArgs | DnsDomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsDomainState | undefined;
            resourceInputs["authoritative"] = state ? state.authoritative : undefined;
            resourceInputs["isDefault"] = state ? state.isDefault : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
        } else {
            const args = argsOrState as DnsDomainArgs | undefined;
            resourceInputs["authoritative"] = args ? args.authoritative : undefined;
            resourceInputs["isDefault"] = args ? args.isDefault : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsDomain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DnsDomain resources.
 */
export interface DnsDomainState {
    /**
     * Boolean value indicating if the new DNS domain is authoritative. Defaults to `false`.
     */
    authoritative?: pulumi.Input<boolean>;
    /**
     * Boolean value indicating if the new DNS domain will be set as the default in the MAAS environment. Defaults to `false`.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * The name of the new DNS domain.
     */
    name?: pulumi.Input<string>;
    /**
     * The default TTL for the new DNS domain.
     */
    ttl?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a DnsDomain resource.
 */
export interface DnsDomainArgs {
    /**
     * Boolean value indicating if the new DNS domain is authoritative. Defaults to `false`.
     */
    authoritative?: pulumi.Input<boolean>;
    /**
     * Boolean value indicating if the new DNS domain will be set as the default in the MAAS environment. Defaults to `false`.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * The name of the new DNS domain.
     */
    name?: pulumi.Input<string>;
    /**
     * The default TTL for the new DNS domain.
     */
    ttl?: pulumi.Input<number>;
}
