// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsRecord extends pulumi.CustomResource {
    /**
     * Get an existing DnsRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsRecordState, opts?: pulumi.CustomResourceOptions): DnsRecord {
        return new DnsRecord(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'maas:index/dnsRecord:DnsRecord';

    /**
     * Returns true if the given object is an instance of DnsRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsRecord.__pulumiType;
    }

    /**
     * The data set for the new DNS record.
     */
    public readonly data!: pulumi.Output<string>;
    /**
     * The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
     */
    public readonly domain!: pulumi.Output<string | undefined>;
    /**
     * The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
     * conflicts with `name` and `domain` arguments.
     */
    public readonly fqdn!: pulumi.Output<string | undefined>;
    /**
     * The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The TTL of the new DNS record.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;
    /**
     * The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a DnsRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsRecordArgs | DnsRecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsRecordState | undefined;
            resourceInputs["data"] = state ? state.data : undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["fqdn"] = state ? state.fqdn : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as DnsRecordArgs | undefined;
            if ((!args || args.data === undefined) && !opts.urn) {
                throw new Error("Missing required property 'data'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["data"] = args ? args.data : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["fqdn"] = args ? args.fqdn : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsRecord.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DnsRecord resources.
 */
export interface DnsRecordState {
    /**
     * The data set for the new DNS record.
     */
    data?: pulumi.Input<string>;
    /**
     * The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
     */
    domain?: pulumi.Input<string>;
    /**
     * The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
     * conflicts with `name` and `domain` arguments.
     */
    fqdn?: pulumi.Input<string>;
    /**
     * The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
     */
    name?: pulumi.Input<string>;
    /**
     * The TTL of the new DNS record.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DnsRecord resource.
 */
export interface DnsRecordArgs {
    /**
     * The data set for the new DNS record.
     */
    data: pulumi.Input<string>;
    /**
     * The domain of the new DNS record. Used in conjunction with `name`. It conflicts with `fqdn` argument.
     */
    domain?: pulumi.Input<string>;
    /**
     * The fully qualified domain name of the new DNS record. This contains the name and the domain of the new DNS record. It
     * conflicts with `name` and `domain` arguments.
     */
    fqdn?: pulumi.Input<string>;
    /**
     * The new DNS record resource name. Used in conjunction with `domain`. It conflicts with `fqdn` argument.
     */
    name?: pulumi.Input<string>;
    /**
     * The TTL of the new DNS record.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The DNS record type. Valid options are: `A/AAAA`, `CNAME`, `MX`, `NS`, `SRV`, `SSHFP`, `TXT`.
     */
    type: pulumi.Input<string>;
}
