// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFabric(args: GetFabricArgs, opts?: pulumi.InvokeOptions): Promise<GetFabricResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("maas:index/getFabric:getFabric", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getFabric.
 */
export interface GetFabricArgs {
    name: string;
}

/**
 * A collection of values returned by getFabric.
 */
export interface GetFabricResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getFabricOutput(args: GetFabricOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFabricResult> {
    return pulumi.output(args).apply((a: any) => getFabric(a, opts))
}

/**
 * A collection of arguments for invoking getFabric.
 */
export interface GetFabricOutputArgs {
    name: pulumi.Input<string>;
}
