// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVlan(args: GetVlanArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("maas:index/getVlan:getVlan", {
        "fabric": args.fabric,
        "vlan": args.vlan,
    }, opts);
}

/**
 * A collection of arguments for invoking getVlan.
 */
export interface GetVlanArgs {
    fabric: string;
    vlan: string;
}

/**
 * A collection of values returned by getVlan.
 */
export interface GetVlanResult {
    readonly dhcpOn: boolean;
    readonly fabric: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly mtu: number;
    readonly name: string;
    readonly space: string;
    readonly vlan: string;
}
export function getVlanOutput(args: GetVlanOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVlanResult> {
    return pulumi.output(args).apply((a: any) => getVlan(a, opts))
}

/**
 * A collection of arguments for invoking getVlan.
 */
export interface GetVlanOutputArgs {
    fabric: pulumi.Input<string>;
    vlan: pulumi.Input<string>;
}
