// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Vlan extends pulumi.CustomResource {
    /**
     * Get an existing Vlan resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VlanState, opts?: pulumi.CustomResourceOptions): Vlan {
        return new Vlan(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'maas:index/vlan:Vlan';

    /**
     * Returns true if the given object is an instance of Vlan.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vlan {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vlan.__pulumiType;
    }

    /**
     * Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
     */
    public readonly dhcpOn!: pulumi.Output<boolean>;
    /**
     * The identifier (name or ID) of the fabric for the new VLAN.
     */
    public readonly fabric!: pulumi.Output<string>;
    /**
     * The MTU to use on the new VLAN. This argument is computed if it's not set.
     */
    public readonly mtu!: pulumi.Output<number>;
    /**
     * The name of the new VLAN. This argument is computed if it's not set.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in
     * the `undefined` space. This argument is computed if it's not set.
     */
    public readonly space!: pulumi.Output<string>;
    /**
     * The traffic segregation ID for the new VLAN.
     */
    public readonly vid!: pulumi.Output<number>;

    /**
     * Create a Vlan resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VlanArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VlanArgs | VlanState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VlanState | undefined;
            resourceInputs["dhcpOn"] = state ? state.dhcpOn : undefined;
            resourceInputs["fabric"] = state ? state.fabric : undefined;
            resourceInputs["mtu"] = state ? state.mtu : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["space"] = state ? state.space : undefined;
            resourceInputs["vid"] = state ? state.vid : undefined;
        } else {
            const args = argsOrState as VlanArgs | undefined;
            if ((!args || args.fabric === undefined) && !opts.urn) {
                throw new Error("Missing required property 'fabric'");
            }
            if ((!args || args.vid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vid'");
            }
            resourceInputs["dhcpOn"] = args ? args.dhcpOn : undefined;
            resourceInputs["fabric"] = args ? args.fabric : undefined;
            resourceInputs["mtu"] = args ? args.mtu : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["space"] = args ? args.space : undefined;
            resourceInputs["vid"] = args ? args.vid : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vlan.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Vlan resources.
 */
export interface VlanState {
    /**
     * Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
     */
    dhcpOn?: pulumi.Input<boolean>;
    /**
     * The identifier (name or ID) of the fabric for the new VLAN.
     */
    fabric?: pulumi.Input<string>;
    /**
     * The MTU to use on the new VLAN. This argument is computed if it's not set.
     */
    mtu?: pulumi.Input<number>;
    /**
     * The name of the new VLAN. This argument is computed if it's not set.
     */
    name?: pulumi.Input<string>;
    /**
     * The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in
     * the `undefined` space. This argument is computed if it's not set.
     */
    space?: pulumi.Input<string>;
    /**
     * The traffic segregation ID for the new VLAN.
     */
    vid?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Vlan resource.
 */
export interface VlanArgs {
    /**
     * Boolean value. Whether or not DHCP should be managed on the new VLAN. This argument is computed if it's not set.
     */
    dhcpOn?: pulumi.Input<boolean>;
    /**
     * The identifier (name or ID) of the fabric for the new VLAN.
     */
    fabric: pulumi.Input<string>;
    /**
     * The MTU to use on the new VLAN. This argument is computed if it's not set.
     */
    mtu?: pulumi.Input<number>;
    /**
     * The name of the new VLAN. This argument is computed if it's not set.
     */
    name?: pulumi.Input<string>;
    /**
     * The space of the new VLAN. Passing in an empty string (or the string `undefined`) will cause the VLAN to be placed in
     * the `undefined` space. This argument is computed if it's not set.
     */
    space?: pulumi.Input<string>;
    /**
     * The traffic segregation ID for the new VLAN.
     */
    vid: pulumi.Input<number>;
}
